global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    env: "mongo-benchmark"

scrape_configs:
  - job_name: "mongo-node"
    static_configs:
      - targets: ["mongo:9100"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongo-exporter:9216"]
    metrics_path: "/metrics"
    scrape_interval: 5s




